### ISSUE TITLE
Define fizzbuzz()

### ISSUE THREAD

**Issue by lojino** [AI-Lab-Team2/team2-fizzbuzz#1]
## Description

define fizzbuzz()

## Tasks

- [x] define function fizzbuzz
- [x] print text in main
- [x] one line (3 & 5 & 15) with if
